# Generated by Django 2.2.17 on 2020-12-06 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_auto_20201206_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='name',
        ),
    ]
